urls = [
    "http://feeds.aps.org/rss/recent/prl.xml",
    "http://feeds.aps.org/rss/recent/pra.xml",
    "http://feeds.aps.org/rss/recent/prx.xml",
    "http://rss.arxiv.org/rss/physics.plasm-ph",
    "http://rss.arxiv.org/rss/physics.comp-ph",
]

research_areas = [
    "strong-field QED (Quantum ElectroDynamics) effects.",
    "particle-in-cell (PIC) simulation. the numerical technique itself, not just researches using PIC.",
]

excluded_areas = [
    "fusion plasma physics.",
]

period = 24

rss_path = "docker/data/rss.xml"